version: '3.8'

services:
  app:
    container_name: 'backend_monitoring_voucher'
    build: 
      context: .
      dockerfile: ./Dockerfile
    # volumes:
    #   - .:/app
    #   - node_modules:/app/node_modules
    environment:
      - PORT=5002
    ports:
      - "9105:5002"
    networks:
      - backend_monitoring_voucher
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

volumes:
  node_modules:

networks:
  backend_monitoring_voucher:
    driver: bridge
