POST http://localhost:5002/v01/monitoring-voucher/api/login
Content-Type: application/json

{
    "identifier":"Admin01",
    "password":"sky123",
    "rememberMe":true
}

###
POST http://localhost:5002/v01/monitoring-voucher/api/create-user
Content-Type: application/json

{
    "SetupRoleId": 14,
    "Name": "testing_001",
    "Gender": "M",
    "Username": "testing_001",
    "Email": "testing_001@testing.com",
    "Phone": "XXXXXXX"
}

###getAll users
GET http://localhost:5002/v01/monitoring-voucher/api/get-all
Content-Type: application/json

###getAll users
GET http://localhost:5002/v01/monitoring-voucher/api/getrole-all
Content-Type: application/json

###getAll users
GET http://localhost:5002/v01/monitoring-voucher/api/getuserbyId
Content-Type: application/json

###getAll users
GET http://localhost:5002/v01/monitoring-voucher/api/logout
Content-Type: application/json

###getAll users
GET http://localhost:5002/v01/monitoring-voucher/api/protected
Content-Type: application/json